//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamWeb.JobHistoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobHistoryDTO", Namespace="http://schemas.datacontract.org/2004/07/ExamWCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class JobHistoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AlumniIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] AlumnisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobHistoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AlumniID {
            get {
                return this.AlumniIDField;
            }
            set {
                if ((this.AlumniIDField.Equals(value) != true)) {
                    this.AlumniIDField = value;
                    this.RaisePropertyChanged("AlumniID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] Alumnis {
            get {
                return this.AlumnisField;
            }
            set {
                if ((object.ReferenceEquals(this.AlumnisField, value) != true)) {
                    this.AlumnisField = value;
                    this.RaisePropertyChanged("Alumnis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobHistoryID {
            get {
                return this.JobHistoryIDField;
            }
            set {
                if ((this.JobHistoryIDField.Equals(value) != true)) {
                    this.JobHistoryIDField = value;
                    this.RaisePropertyChanged("JobHistoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobHistoryService.IJobHistoryService")]
    public interface IJobHistoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/GetJobHistories", ReplyAction="http://tempuri.org/IJobHistoryService/GetJobHistoriesResponse")]
        ExamWeb.JobHistoryService.JobHistoryDTO[] GetJobHistories(int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/GetJobHistories", ReplyAction="http://tempuri.org/IJobHistoryService/GetJobHistoriesResponse")]
        System.Threading.Tasks.Task<ExamWeb.JobHistoryService.JobHistoryDTO[]> GetJobHistoriesAsync(int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/GetJobHistoryByID", ReplyAction="http://tempuri.org/IJobHistoryService/GetJobHistoryByIDResponse")]
        ExamWeb.JobHistoryService.JobHistoryDTO GetJobHistoryByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/GetJobHistoryByID", ReplyAction="http://tempuri.org/IJobHistoryService/GetJobHistoryByIDResponse")]
        System.Threading.Tasks.Task<ExamWeb.JobHistoryService.JobHistoryDTO> GetJobHistoryByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/InsertJobHistory", ReplyAction="http://tempuri.org/IJobHistoryService/InsertJobHistoryResponse")]
        void InsertJobHistory(ExamWeb.JobHistoryService.JobHistoryDTO jobHistoryDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/InsertJobHistory", ReplyAction="http://tempuri.org/IJobHistoryService/InsertJobHistoryResponse")]
        System.Threading.Tasks.Task InsertJobHistoryAsync(ExamWeb.JobHistoryService.JobHistoryDTO jobHistoryDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/UpdateJobHistory", ReplyAction="http://tempuri.org/IJobHistoryService/UpdateJobHistoryResponse")]
        void UpdateJobHistory(ExamWeb.JobHistoryService.JobHistoryDTO jobHistoryDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/UpdateJobHistory", ReplyAction="http://tempuri.org/IJobHistoryService/UpdateJobHistoryResponse")]
        System.Threading.Tasks.Task UpdateJobHistoryAsync(ExamWeb.JobHistoryService.JobHistoryDTO jobHistoryDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/DeleteJobHistory", ReplyAction="http://tempuri.org/IJobHistoryService/DeleteJobHistoryResponse")]
        void DeleteJobHistory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryService/DeleteJobHistory", ReplyAction="http://tempuri.org/IJobHistoryService/DeleteJobHistoryResponse")]
        System.Threading.Tasks.Task DeleteJobHistoryAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobHistoryServiceChannel : ExamWeb.JobHistoryService.IJobHistoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobHistoryServiceClient : System.ServiceModel.ClientBase<ExamWeb.JobHistoryService.IJobHistoryService>, ExamWeb.JobHistoryService.IJobHistoryService {
        
        public JobHistoryServiceClient() {
        }
        
        public JobHistoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobHistoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobHistoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobHistoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExamWeb.JobHistoryService.JobHistoryDTO[] GetJobHistories(int alumniID) {
            return base.Channel.GetJobHistories(alumniID);
        }
        
        public System.Threading.Tasks.Task<ExamWeb.JobHistoryService.JobHistoryDTO[]> GetJobHistoriesAsync(int alumniID) {
            return base.Channel.GetJobHistoriesAsync(alumniID);
        }
        
        public ExamWeb.JobHistoryService.JobHistoryDTO GetJobHistoryByID(int id) {
            return base.Channel.GetJobHistoryByID(id);
        }
        
        public System.Threading.Tasks.Task<ExamWeb.JobHistoryService.JobHistoryDTO> GetJobHistoryByIDAsync(int id) {
            return base.Channel.GetJobHistoryByIDAsync(id);
        }
        
        public void InsertJobHistory(ExamWeb.JobHistoryService.JobHistoryDTO jobHistoryDTO) {
            base.Channel.InsertJobHistory(jobHistoryDTO);
        }
        
        public System.Threading.Tasks.Task InsertJobHistoryAsync(ExamWeb.JobHistoryService.JobHistoryDTO jobHistoryDTO) {
            return base.Channel.InsertJobHistoryAsync(jobHistoryDTO);
        }
        
        public void UpdateJobHistory(ExamWeb.JobHistoryService.JobHistoryDTO jobHistoryDTO) {
            base.Channel.UpdateJobHistory(jobHistoryDTO);
        }
        
        public System.Threading.Tasks.Task UpdateJobHistoryAsync(ExamWeb.JobHistoryService.JobHistoryDTO jobHistoryDTO) {
            return base.Channel.UpdateJobHistoryAsync(jobHistoryDTO);
        }
        
        public void DeleteJobHistory(int id) {
            base.Channel.DeleteJobHistory(id);
        }
        
        public System.Threading.Tasks.Task DeleteJobHistoryAsync(int id) {
            return base.Channel.DeleteJobHistoryAsync(id);
        }
    }
}
