//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamWeb.JobAttachmentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobAttachmentDTO", Namespace="http://schemas.datacontract.org/2004/07/ExamWCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class JobAttachmentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumniIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlumniNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttachmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentTypeDisplayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte AttachmentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid JobIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SelectedAttachmentTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumniID {
            get {
                return this.AlumniIDField;
            }
            set {
                if ((this.AlumniIDField.Equals(value) != true)) {
                    this.AlumniIDField = value;
                    this.RaisePropertyChanged("AlumniID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlumniName {
            get {
                return this.AlumniNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlumniNameField, value) != true)) {
                    this.AlumniNameField = value;
                    this.RaisePropertyChanged("AlumniName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttachmentID {
            get {
                return this.AttachmentIDField;
            }
            set {
                if ((this.AttachmentIDField.Equals(value) != true)) {
                    this.AttachmentIDField = value;
                    this.RaisePropertyChanged("AttachmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentTypeDisplay {
            get {
                return this.AttachmentTypeDisplayField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentTypeDisplayField, value) != true)) {
                    this.AttachmentTypeDisplayField = value;
                    this.RaisePropertyChanged("AttachmentTypeDisplay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte AttachmentTypeID {
            get {
                return this.AttachmentTypeIDField;
            }
            set {
                if ((this.AttachmentTypeIDField.Equals(value) != true)) {
                    this.AttachmentTypeIDField = value;
                    this.RaisePropertyChanged("AttachmentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid JobID {
            get {
                return this.JobIDField;
            }
            set {
                if ((this.JobIDField.Equals(value) != true)) {
                    this.JobIDField = value;
                    this.RaisePropertyChanged("JobID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SelectedAttachmentTypes {
            get {
                return this.SelectedAttachmentTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedAttachmentTypesField, value) != true)) {
                    this.SelectedAttachmentTypesField = value;
                    this.RaisePropertyChanged("SelectedAttachmentTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobAttachmentService.IJobAttachmentService")]
    public interface IJobAttachmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAttachmentService/GetCandidates", ReplyAction="http://tempuri.org/IJobAttachmentService/GetCandidatesResponse")]
        ExamWeb.JobAttachmentService.JobAttachmentDTO[] GetCandidates(System.Guid jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAttachmentService/GetCandidates", ReplyAction="http://tempuri.org/IJobAttachmentService/GetCandidatesResponse")]
        System.Threading.Tasks.Task<ExamWeb.JobAttachmentService.JobAttachmentDTO[]> GetCandidatesAsync(System.Guid jobID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobAttachmentServiceChannel : ExamWeb.JobAttachmentService.IJobAttachmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobAttachmentServiceClient : System.ServiceModel.ClientBase<ExamWeb.JobAttachmentService.IJobAttachmentService>, ExamWeb.JobAttachmentService.IJobAttachmentService {
        
        public JobAttachmentServiceClient() {
        }
        
        public JobAttachmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobAttachmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobAttachmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobAttachmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExamWeb.JobAttachmentService.JobAttachmentDTO[] GetCandidates(System.Guid jobID) {
            return base.Channel.GetCandidates(jobID);
        }
        
        public System.Threading.Tasks.Task<ExamWeb.JobAttachmentService.JobAttachmentDTO[]> GetCandidatesAsync(System.Guid jobID) {
            return base.Channel.GetCandidatesAsync(jobID);
        }
    }
}
