//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamWeb.AlumniService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumniDTO", Namespace="http://schemas.datacontract.org/2004/07/ExamWCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class AlumniDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumniIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApplyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamWeb.AlumniService.AttachmentDTO[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DistrictIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] DistrictsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] FacultiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacultyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyMajorNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GraduationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HobbyDisplayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedInProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MajorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] MajorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SelectedHobbiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] StatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumniID {
            get {
                return this.AlumniIDField;
            }
            set {
                if ((this.AlumniIDField.Equals(value) != true)) {
                    this.AlumniIDField = value;
                    this.RaisePropertyChanged("AlumniID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApplyDate {
            get {
                return this.ApplyDateField;
            }
            set {
                if ((this.ApplyDateField.Equals(value) != true)) {
                    this.ApplyDateField = value;
                    this.RaisePropertyChanged("ApplyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamWeb.AlumniService.AttachmentDTO[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Degree {
            get {
                return this.DegreeField;
            }
            set {
                if ((object.ReferenceEquals(this.DegreeField, value) != true)) {
                    this.DegreeField = value;
                    this.RaisePropertyChanged("Degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DistrictID {
            get {
                return this.DistrictIDField;
            }
            set {
                if ((this.DistrictIDField.Equals(value) != true)) {
                    this.DistrictIDField = value;
                    this.RaisePropertyChanged("DistrictID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictNames {
            get {
                return this.DistrictNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNamesField, value) != true)) {
                    this.DistrictNamesField = value;
                    this.RaisePropertyChanged("DistrictNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] Districts {
            get {
                return this.DistrictsField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictsField, value) != true)) {
                    this.DistrictsField = value;
                    this.RaisePropertyChanged("Districts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] Faculties {
            get {
                return this.FacultiesField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultiesField, value) != true)) {
                    this.FacultiesField = value;
                    this.RaisePropertyChanged("Faculties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacultyID {
            get {
                return this.FacultyIDField;
            }
            set {
                if ((this.FacultyIDField.Equals(value) != true)) {
                    this.FacultyIDField = value;
                    this.RaisePropertyChanged("FacultyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyMajorNames {
            get {
                return this.FacultyMajorNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyMajorNamesField, value) != true)) {
                    this.FacultyMajorNamesField = value;
                    this.RaisePropertyChanged("FacultyMajorNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyNames {
            get {
                return this.FacultyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNamesField, value) != true)) {
                    this.FacultyNamesField = value;
                    this.RaisePropertyChanged("FacultyNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullAddresses {
            get {
                return this.FullAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.FullAddressesField, value) != true)) {
                    this.FullAddressesField = value;
                    this.RaisePropertyChanged("FullAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNames {
            get {
                return this.FullNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNamesField, value) != true)) {
                    this.FullNamesField = value;
                    this.RaisePropertyChanged("FullNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GraduationYear {
            get {
                return this.GraduationYearField;
            }
            set {
                if ((this.GraduationYearField.Equals(value) != true)) {
                    this.GraduationYearField = value;
                    this.RaisePropertyChanged("GraduationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HobbyDisplay {
            get {
                return this.HobbyDisplayField;
            }
            set {
                if ((object.ReferenceEquals(this.HobbyDisplayField, value) != true)) {
                    this.HobbyDisplayField = value;
                    this.RaisePropertyChanged("HobbyDisplay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkedInProfile {
            get {
                return this.LinkedInProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedInProfileField, value) != true)) {
                    this.LinkedInProfileField = value;
                    this.RaisePropertyChanged("LinkedInProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MajorID {
            get {
                return this.MajorIDField;
            }
            set {
                if ((this.MajorIDField.Equals(value) != true)) {
                    this.MajorIDField = value;
                    this.RaisePropertyChanged("MajorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorNames {
            get {
                return this.MajorNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorNamesField, value) != true)) {
                    this.MajorNamesField = value;
                    this.RaisePropertyChanged("MajorNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] Majors {
            get {
                return this.MajorsField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorsField, value) != true)) {
                    this.MajorsField = value;
                    this.RaisePropertyChanged("Majors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoName {
            get {
                return this.PhotoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoNameField, value) != true)) {
                    this.PhotoNameField = value;
                    this.RaisePropertyChanged("PhotoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath {
            get {
                return this.PhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPathField, value) != true)) {
                    this.PhotoPathField = value;
                    this.RaisePropertyChanged("PhotoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SelectedHobbies {
            get {
                return this.SelectedHobbiesField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedHobbiesField, value) != true)) {
                    this.SelectedHobbiesField = value;
                    this.RaisePropertyChanged("SelectedHobbies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateNames {
            get {
                return this.StateNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNamesField, value) != true)) {
                    this.StateNamesField = value;
                    this.RaisePropertyChanged("StateNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentDTO", Namespace="http://schemas.datacontract.org/2004/07/ExamWCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class AttachmentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistrictDTO", Namespace="http://schemas.datacontract.org/2004/07/ExamWCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class DistrictDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistrictIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] StatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistrictID {
            get {
                return this.DistrictIDField;
            }
            set {
                if ((this.DistrictIDField.Equals(value) != true)) {
                    this.DistrictIDField = value;
                    this.RaisePropertyChanged("DistrictID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateNames {
            get {
                return this.StateNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNamesField, value) != true)) {
                    this.StateNamesField = value;
                    this.RaisePropertyChanged("StateNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateDTO", Namespace="http://schemas.datacontract.org/2004/07/ExamWCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class StateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HobbyDTO", Namespace="http://schemas.datacontract.org/2004/07/ExamWCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class HobbyDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HobbyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HobbyID {
            get {
                return this.HobbyIDField;
            }
            set {
                if ((this.HobbyIDField.Equals(value) != true)) {
                    this.HobbyIDField = value;
                    this.RaisePropertyChanged("HobbyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlumniService.IAlumniService")]
    public interface IAlumniService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAlumnis", ReplyAction="http://tempuri.org/IAlumniService/GetAlumnisResponse")]
        ExamWeb.AlumniService.AlumniDTO[] GetAlumnis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAlumnis", ReplyAction="http://tempuri.org/IAlumniService/GetAlumnisResponse")]
        System.Threading.Tasks.Task<ExamWeb.AlumniService.AlumniDTO[]> GetAlumnisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistrictsByStateID", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictsByStateIDResponse")]
        ExamWeb.AlumniService.DistrictDTO[] GetDistrictsByStateID(int stateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistrictsByStateID", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictsByStateIDResponse")]
        System.Threading.Tasks.Task<ExamWeb.AlumniService.DistrictDTO[]> GetDistrictsByStateIDAsync(int stateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetStates", ReplyAction="http://tempuri.org/IAlumniService/GetStatesResponse")]
        ExamWeb.AlumniService.StateDTO[] GetStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetStates", ReplyAction="http://tempuri.org/IAlumniService/GetStatesResponse")]
        System.Threading.Tasks.Task<ExamWeb.AlumniService.StateDTO[]> GetStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistricts", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictsResponse")]
        ExamWeb.AlumniService.DistrictDTO[] GetDistricts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistricts", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictsResponse")]
        System.Threading.Tasks.Task<ExamWeb.AlumniService.DistrictDTO[]> GetDistrictsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetHobbys", ReplyAction="http://tempuri.org/IAlumniService/GetHobbysResponse")]
        ExamWeb.AlumniService.HobbyDTO[] GetHobbys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetHobbys", ReplyAction="http://tempuri.org/IAlumniService/GetHobbysResponse")]
        System.Threading.Tasks.Task<ExamWeb.AlumniService.HobbyDTO[]> GetHobbysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetHobbyIDByName", ReplyAction="http://tempuri.org/IAlumniService/GetHobbyIDByNameResponse")]
        int GetHobbyIDByName(string hobbyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetHobbyIDByName", ReplyAction="http://tempuri.org/IAlumniService/GetHobbyIDByNameResponse")]
        System.Threading.Tasks.Task<int> GetHobbyIDByNameAsync(string hobbyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAlumniByID", ReplyAction="http://tempuri.org/IAlumniService/GetAlumniByIDResponse")]
        ExamWeb.AlumniService.AlumniDTO GetAlumniByID(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetAlumniByID", ReplyAction="http://tempuri.org/IAlumniService/GetAlumniByIDResponse")]
        System.Threading.Tasks.Task<ExamWeb.AlumniService.AlumniDTO> GetAlumniByIDAsync(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/InsertAlumni", ReplyAction="http://tempuri.org/IAlumniService/InsertAlumniResponse")]
        void InsertAlumni(ExamWeb.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/InsertAlumni", ReplyAction="http://tempuri.org/IAlumniService/InsertAlumniResponse")]
        System.Threading.Tasks.Task InsertAlumniAsync(ExamWeb.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpdateAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpdateAlumniResponse")]
        void UpdateAlumni(ExamWeb.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpdateAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpdateAlumniResponse")]
        System.Threading.Tasks.Task UpdateAlumniAsync(ExamWeb.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/DeleteAlumni", ReplyAction="http://tempuri.org/IAlumniService/DeleteAlumniResponse")]
        void DeleteAlumni(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/DeleteAlumni", ReplyAction="http://tempuri.org/IAlumniService/DeleteAlumniResponse")]
        System.Threading.Tasks.Task DeleteAlumniAsync(int alumniId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetStateIDByName", ReplyAction="http://tempuri.org/IAlumniService/GetStateIDByNameResponse")]
        int GetStateIDByName(string stateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetStateIDByName", ReplyAction="http://tempuri.org/IAlumniService/GetStateIDByNameResponse")]
        System.Threading.Tasks.Task<int> GetStateIDByNameAsync(string stateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistrictIDByName", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictIDByNameResponse")]
        int GetDistrictIDByName(string districtName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/GetDistrictIDByName", ReplyAction="http://tempuri.org/IAlumniService/GetDistrictIDByNameResponse")]
        System.Threading.Tasks.Task<int> GetDistrictIDByNameAsync(string districtName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/ImportFromExcel", ReplyAction="http://tempuri.org/IAlumniService/ImportFromExcelResponse")]
        void ImportFromExcel(ExamWeb.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/ImportFromExcel", ReplyAction="http://tempuri.org/IAlumniService/ImportFromExcelResponse")]
        System.Threading.Tasks.Task ImportFromExcelAsync(ExamWeb.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpsertMultipleAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpsertMultipleAlumniResponse")]
        void UpsertMultipleAlumni(ExamWeb.AlumniService.AlumniDTO[] alumnis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpsertMultipleAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpsertMultipleAlumniResponse")]
        System.Threading.Tasks.Task UpsertMultipleAlumniAsync(ExamWeb.AlumniService.AlumniDTO[] alumnis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpsertAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpsertAlumniResponse")]
        void UpsertAlumni(ExamWeb.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniService/UpsertAlumni", ReplyAction="http://tempuri.org/IAlumniService/UpsertAlumniResponse")]
        System.Threading.Tasks.Task UpsertAlumniAsync(ExamWeb.AlumniService.AlumniDTO alumni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumniServiceChannel : ExamWeb.AlumniService.IAlumniService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumniServiceClient : System.ServiceModel.ClientBase<ExamWeb.AlumniService.IAlumniService>, ExamWeb.AlumniService.IAlumniService {
        
        public AlumniServiceClient() {
        }
        
        public AlumniServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumniServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumniServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumniServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExamWeb.AlumniService.AlumniDTO[] GetAlumnis() {
            return base.Channel.GetAlumnis();
        }
        
        public System.Threading.Tasks.Task<ExamWeb.AlumniService.AlumniDTO[]> GetAlumnisAsync() {
            return base.Channel.GetAlumnisAsync();
        }
        
        public ExamWeb.AlumniService.DistrictDTO[] GetDistrictsByStateID(int stateID) {
            return base.Channel.GetDistrictsByStateID(stateID);
        }
        
        public System.Threading.Tasks.Task<ExamWeb.AlumniService.DistrictDTO[]> GetDistrictsByStateIDAsync(int stateID) {
            return base.Channel.GetDistrictsByStateIDAsync(stateID);
        }
        
        public ExamWeb.AlumniService.StateDTO[] GetStates() {
            return base.Channel.GetStates();
        }
        
        public System.Threading.Tasks.Task<ExamWeb.AlumniService.StateDTO[]> GetStatesAsync() {
            return base.Channel.GetStatesAsync();
        }
        
        public ExamWeb.AlumniService.DistrictDTO[] GetDistricts() {
            return base.Channel.GetDistricts();
        }
        
        public System.Threading.Tasks.Task<ExamWeb.AlumniService.DistrictDTO[]> GetDistrictsAsync() {
            return base.Channel.GetDistrictsAsync();
        }
        
        public ExamWeb.AlumniService.HobbyDTO[] GetHobbys() {
            return base.Channel.GetHobbys();
        }
        
        public System.Threading.Tasks.Task<ExamWeb.AlumniService.HobbyDTO[]> GetHobbysAsync() {
            return base.Channel.GetHobbysAsync();
        }
        
        public int GetHobbyIDByName(string hobbyName) {
            return base.Channel.GetHobbyIDByName(hobbyName);
        }
        
        public System.Threading.Tasks.Task<int> GetHobbyIDByNameAsync(string hobbyName) {
            return base.Channel.GetHobbyIDByNameAsync(hobbyName);
        }
        
        public ExamWeb.AlumniService.AlumniDTO GetAlumniByID(int alumniId) {
            return base.Channel.GetAlumniByID(alumniId);
        }
        
        public System.Threading.Tasks.Task<ExamWeb.AlumniService.AlumniDTO> GetAlumniByIDAsync(int alumniId) {
            return base.Channel.GetAlumniByIDAsync(alumniId);
        }
        
        public void InsertAlumni(ExamWeb.AlumniService.AlumniDTO alumni) {
            base.Channel.InsertAlumni(alumni);
        }
        
        public System.Threading.Tasks.Task InsertAlumniAsync(ExamWeb.AlumniService.AlumniDTO alumni) {
            return base.Channel.InsertAlumniAsync(alumni);
        }
        
        public void UpdateAlumni(ExamWeb.AlumniService.AlumniDTO alumni) {
            base.Channel.UpdateAlumni(alumni);
        }
        
        public System.Threading.Tasks.Task UpdateAlumniAsync(ExamWeb.AlumniService.AlumniDTO alumni) {
            return base.Channel.UpdateAlumniAsync(alumni);
        }
        
        public void DeleteAlumni(int alumniId) {
            base.Channel.DeleteAlumni(alumniId);
        }
        
        public System.Threading.Tasks.Task DeleteAlumniAsync(int alumniId) {
            return base.Channel.DeleteAlumniAsync(alumniId);
        }
        
        public int GetStateIDByName(string stateName) {
            return base.Channel.GetStateIDByName(stateName);
        }
        
        public System.Threading.Tasks.Task<int> GetStateIDByNameAsync(string stateName) {
            return base.Channel.GetStateIDByNameAsync(stateName);
        }
        
        public int GetDistrictIDByName(string districtName) {
            return base.Channel.GetDistrictIDByName(districtName);
        }
        
        public System.Threading.Tasks.Task<int> GetDistrictIDByNameAsync(string districtName) {
            return base.Channel.GetDistrictIDByNameAsync(districtName);
        }
        
        public void ImportFromExcel(ExamWeb.AlumniService.AlumniDTO alumni) {
            base.Channel.ImportFromExcel(alumni);
        }
        
        public System.Threading.Tasks.Task ImportFromExcelAsync(ExamWeb.AlumniService.AlumniDTO alumni) {
            return base.Channel.ImportFromExcelAsync(alumni);
        }
        
        public void UpsertMultipleAlumni(ExamWeb.AlumniService.AlumniDTO[] alumnis) {
            base.Channel.UpsertMultipleAlumni(alumnis);
        }
        
        public System.Threading.Tasks.Task UpsertMultipleAlumniAsync(ExamWeb.AlumniService.AlumniDTO[] alumnis) {
            return base.Channel.UpsertMultipleAlumniAsync(alumnis);
        }
        
        public void UpsertAlumni(ExamWeb.AlumniService.AlumniDTO alumni) {
            base.Channel.UpsertAlumni(alumni);
        }
        
        public System.Threading.Tasks.Task UpsertAlumniAsync(ExamWeb.AlumniService.AlumniDTO alumni) {
            return base.Channel.UpsertAlumniAsync(alumni);
        }
    }
}
